name: fre-cli
channels:
  - defaults
  - conda-forge
  - noaa-gfdl
dependencies:
  - python
  - pip
  - click
  - pyyaml
  - pylint
  - jsonschema
  - noaa-gfdl::fre-nctools
  - noaa-gfdl::catalogbuilder
  - conda-forge::git
  - conda-forge::nccmp
  - conda-forge::cylc-flow>=8.2.0
  - conda-forge::cylc-rose
  - conda-forge::metomi-rose
  - conda-forge::cmor
  - conda-forge::cylc-uiserver
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::python-cdo
  - conda-forge::cdo>=2.0.0
  - pip:
    - GitPython
