name: fre-cli
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - python==3.10
  - pip
  - click
  - pyyaml
  - pylint
  - jsonschema
  - cftime
  - noaa-gfdl::fre-nctools
  - noaa-gfdl::catalogbuilder
  - noaa-gfdl::analysis_scripts
  - conda-forge::nccmp
  - conda-forge::cylc-flow>=8.2.0
  - conda-forge::cylc-rose
  - conda-forge::metomi-rose
  - conda-forge::cmor>=3.9.0
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::python-cdo
  - conda-forge::cdo>=2.0.0
