name: fre-cli
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - python>=3.11
  - noaa-gfdl::analysis_scripts==0.0.1
  - noaa-gfdl::catalogbuilder==2025.01.01
#  - noaa-gfdl::fre-nctools==2022.02.01
  - conda-forge::cdo>=2
  - conda-forge::cftime
  - conda-forge::click>=8.2
  - conda-forge::cmor>=3.14
  - conda-forge::cylc-flow>=8.2
  - conda-forge::cylc-rose
  - conda-forge::jinja2>=3
  - conda-forge::jsonschema
  - conda-forge::metomi-rose
  - conda-forge::nccmp
  - conda-forge::numpy==1.26.4
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::pylint
  - conda-forge::python-cdo
  - conda-forge::pyyaml
  - conda-forge::xarray>=2024.*
  - conda-forge::netcdf4>=1.7.*
