name: fre-cli
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - python==3.11
  - pip
  - noaa-gfdl::analysis_scripts
  - noaa-gfdl::catalogbuilder
  - noaa-gfdl::fre-nctools
  - conda-forge::click
  - conda-forge::cylc-flow>=8.2.0
  - conda-forge::cylc-rose
  - conda-forge::cmor>=3.10.0
  - conda-forge::cdo>=2.0.0
  - conda-forge::jsonschema
  - conda-forge::metomi-rose
  - conda-forge::nccmp
  - conda-forge::pylint
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::python-cdo
  - conda-forge::cftime
  - conda-forge::pyyaml
