name: publish_conda
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fre-cli:miniconda24.7.1_gcc14.2.0
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run Conda to Build and Publish
        run: |
          conda config --append channels conda-forge
          conda config --append channels noaa-gfdl
          conda install conda-build anaconda-client conda-verify
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          conda config --set anaconda_upload yes
          conda build .
